version: 2.1

commands:
  configure-git:
    steps:
      - run: git config --global user.name "CI Bot"
      - run: git config --global user.email "ci@noreply.circleci.com"

  install-deps:
    parameters:
      python_version:
        type: string
    steps:
      - restore_cache:
          name: restore dependency cache
          keys:
            - uv-py<<parameters.python_version>>-{{ checksum "uv.lock" }}
      - run: uv sync --python=<<parameters.python_version>>
      - save_cache:
          name: save dependency cache
          key: uv-py<<parameters.python_version>>-{{ checksum "uv.lock" }}
          paths:
            - .venv

jobs:
  test:
    docker:
      - image: cimg/python:<<parameters.python_version>>
    parameters:
      python_version:
        type: string
    steps:
      - checkout
      - install-deps:
          python_version: <<parameters.python_version>>
      - run: uv run inv check

  bump:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - configure-git
      - add_ssh_keys
      - install-deps:
          python_version: "3.9"
      - run: uv run inv bump
      - run: |
          git push origin $CIRCLE_BRANCH
          git push --tags

  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - configure-git
      - install-deps:
          python_version: "3.9"
      - run: uv run inv build
      - run: uv run inv publish

workflows:
  ci:
    jobs:
      - test:
          matrix:
            parameters:
              python_version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
      - bump:
          requires:
            - test
          filters:
            branches:
              only: main
  release:
    jobs:
      - test:
          matrix:
            parameters:
              python_version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*$/
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*$/
